version: "3.4"
services:
  ms-ao:
    ports:
      - "8089:8089"
    image: ms-ao:latest
    networks:
      - prestalink
    depends_on:
      - config
      - mysqldb
      - Euruka
      - gateway
  gateway:
    image: ms-gateway:latest
    ports:
      - "8765:8765"
    networks:
      - prestalink
    restart: unless-stopped
    depends_on:
      - Euruka
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flowable-spring-boot
    networks:
      - prestalink
    ports:
      - 3306:3306
  Euruka:
    ports:
      - "8761:8761"
    image: ms-eureka:latest
    networks:
      - prestalink
  config:
    ports:
      - "8888:8888"
    image: ms-config:latest
    networks:
      - prestalink
networks:
  prestalink:

